# Generated by Django 4.2.1 on 2023-05-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('korime', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('lozinka', models.CharField(max_length=30)),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('admin', models.IntegerField()),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=50)),
                ('sadrzaj', models.CharField(max_length=500)),
                ('datum', models.DateField()),
            ],
            options={
                'db_table': 'vest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.CharField(max_length=500)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vijesti.autor')),
                ('vest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vijesti.vest')),
            ],
            options={
                'db_table': 'komentar',
            },
        ),
    ]
